title: ✨Happy Smart Light✨
description: >-
  Chuyên tư vấn giải pháp kỹ thuật, thiết kế, led Decor, quảng cáo,
  sự kiện, led visual poi đạo cụ sân khấu, trình diển ánh sáng.
url: "https://happysmartlight.com"
baseurl: "" # the subpath of your site, e.g. /blog
lang: "vi"
navbar-links:
  🔖PostNews: post-news
  🔥Mạch điều khiển:
    url: /controller-chip
    children:
      - Điều khiển LED Pixel: controller-chip#ledPixel
      - Điều khiển LED Cabin: controller-chip#ledMatrix
      - Phát - thu sóng: controller-chip#signalWifi
  💡Visual LED: 
    url: /poi-tools
    children:
    - Happy POI: poi-tools#visualPoi
    - Happy HOOP: poi-tools#visualHoop
    - Nguồn và Pin: poi-tools#power
    - Khác: poi-tools#other
  💡Đạo cụ LED: 
    url: /led-props
    children:
    - Led Pixel: led-props#ledPixel
    - Led Module: led-props#ledMatrix
    - Laser Series: led-props#laser
    - Nguồn và Pin: led-props#power
    - Khác: led-props#other
  ❓Về HSL:
    url: /service
    children:
    - Liên hệ với HSL: aboutme
    - Đào tạo: service#training
    - Đối tác với HSL: service#partner
    - Tư vấn, thiết kế: service#consult
    - Led Decor: service#decor
    - Led Dance: service#dance
    - Led Biển Hiệu: service#advertising
    - Dịch vụ Order: service#order
  # 🗝️Tags: tags #thay thế bằng nút tìm kiếm.
avatar: "/img/Picture-HSL/logo_hsl.png"
author:
  name: "\U0001F525HAPPY SMART LIGHT\U0001F525"
  rss: true
  email: happysmartlight@outlook.com
  facebook: happysmartlight
  github: happysmartlight
  instagram: nguyen.duy.bang
  youtube: '@HappySmartLight'
  telephone: 0784140494
  tiktok: '@denthongminhhappy'
company: "CÔNG TY TNHH THƯƠNG MẠI VÀ CÔNG NGHỆ HAPPY SMART LIGHT"
company_EN: "HAPPY SMART LIGHT TRADING AND TECHNOLOGY COMPANY LIMITED"
company_SHORT_NAME: "✨HAPPY SMART LIGHT✨"
director: "Nguyễn Duy Bằng"
established: "2025-01-13"
Tax-code: "3502535621"
address-1: "Sảnh S6.03, Vinhomes Grand Park, P. Long Bình, TP. Hồ Chí Minh"
address-2: "Số 42 Hà Đức Trọng, P. Bà Rịa, TP. Hồ Chí Minh"
map-address-1: https://maps.app.goo.gl/rMTH9mqSYXBorpZY9
map-address-2: https://maps.app.goo.gl/rjQizjWgt69466Es6
footer-links-active:
  rss: false
  facebook: true
  email: true
  telephone: true
  youtube: true
  tiktok: true
  map-address-1: false
  map-address-2: false
share-links-active:
  facebook: true
  linkedin: true
disqus: bang-nguyen-blog
google_analytics: G-NX3V2C477N
gtm: GTM-PSCP4JVR
fb_app_id: '721347795190980'
excerpt_length: 50
title-separator: '-'
timezone: Asia/Bangkok
markdown: kramdown
highlighter: rouge
permalink: '/:year-:month-:day-:title/'
paginate: 8
kramdown:
  input: GFM
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      sitemap: true
      comments: true
      social-share: true
  - scope:
      path: ''
    values:
      layout: page
      show-avatar: true
link-tags: true
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - LICENSE
  - README.md
  - Vagrantfile
  - vendor/
collections:
  post-news:
    output: true       # Bài viết trong collection này sẽ được xuất ra file HTML
    permalink: /post-news/:name/  # Định nghĩa cấu trúc URL cho bài viết
  poi-tools:
    output: true       # Bài viết trong collection này sẽ được xuất ra file HTML
    permalink: /poi-tools/:name/  # Định nghĩa cấu trúc URL cho bài viết
  led-props:
    output: true
    permalink: /led-props/:name/
  controller-chip:
    output: true
    permalink: /controller-chip/:name/
  service:
    output: true
    permalink: /service/:name/

feed:
  collections:
    - post-news
    - poi-tools
    - led-props
    - controller-chip
    - service

# Optionally, add permalink defaults (for better structure)
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
