name: Lighthouse CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Chrome
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-chrome-${{ hashFiles('google-chrome-stable_current_amd64.deb') }}
          restore-keys: |
            ${{ runner.os }}-chrome-

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://happysmartlight.github.io/
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
